"""add_page_dimensions_to_chunks

Revision ID: 41135b71bb05
Revises: 88b9f4a8d939
Create Date: 2026-08-07 17:22:40.428708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41135b71bb05'
down_revision: Union[str, Sequence[str], None] = '88b9f4a8d939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('page_width', sa.Float(), nullable=True))
    op.add_column('chunks', sa.Column('page_height', sa.Float(), nullable=True))
    op.alter_column('chunks', 'bboxes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'bboxes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('chunks', 'page_height')
    op.drop_column('chunks', 'page_width')
    # ### end Alembic commands ###
