"""add document metadata

Revision ID: 7a67c770c4b6
Revises: 639dc38aae5a
Create Date: 2026-08-01 12:17:10.183998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a67c770c4b6'
down_revision: Union[str, Sequence[str], None] = '639dc38aae5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.Text(), nullable=False))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'file_name')
    op.drop_column('documents', 'source')
    # ### end Alembic commands ###
