"""add page metadata to chunks

Revision ID: 88b9f4a8d939
Revises: c3d1f56cb249
Create Date: 2026-08-07 15:52:55.004102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b9f4a8d939'
down_revision: Union[str, Sequence[str], None] = 'c3d1f56cb249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "chunks",
        sa.Column(
            "page_number",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
    )

    op.add_column(
        "chunks",
        sa.Column(
            "bboxes",
            sa.JSON(),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'bboxes')
    op.drop_column('chunks', 'page_number')
    # ### end Alembic commands ###
