"""add is_pinned to conversations

Revision ID: c3d1f56cb249
Revises: 1d87bc8290d6
Create Date: 2026-08-04 14:35:56.633547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d1f56cb249'
down_revision: Union[str, Sequence[str], None] = '1d87bc8290d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_pinned')
    # ### end Alembic commands ###
